default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: LICENSE
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: uvx run isort --settings-path pyproject.toml
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: black
        name: black
        entry: uvx run black --config pyproject.toml
        types: [python]
        language: system
