name: "Check PR title"
on:
  pull_request:
    types: [edited, opened, synchronize, reopened]

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login != 'allcontributors[bot]' }}
    steps:
      # Echo the user's login
      - name: Echo user login
        run: echo ${{ github.event.pull_request.user.login }}

      - uses: naveenk1223/action-pr-title@master
        with:
          # ^                       Start of string
          # [A-Z]                   First character must be an uppercase ASCII letter
          # [a-zA-Z]*               Followed by zero or more ASCII letters
          # (?<![^s]s)              Negative lookbehind: disallow a single 's' at the end of the first word
          # ( .+)+                  At least one space and one or more characters (requires more words)
          # [^.]                    Final character must not be a period
          # $                       End of string
          regex: "^[A-Z][a-zA-Z]*(?<![^s]s)( .+)+[^.]$"
          # Valid titles:
          # - "Do something"
          # - "Address something"
          # Invalid title:
          # - "do something"
          # - "Do something."
          # - "Does something"
          # - "Do"
          # - "Addresses something"
          min_length: 10
          max_length: 72
