name: Docs Publish
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --only-group doc

      - name: Deploy docs
        run: uv run --only-group doc mkdocs gh-deploy --force
